import { expect, test } from '@playwright/test'

test('one quiet source becomes focused attention without losing operator context', async ({ page }, testInfo) => {
  await page.setViewportSize({ width: 1440, height: 900 })
  await page.goto('/monitor')
  await expect(page.getByRole('heading', { level: 1 })).toHaveText('Monitoring Station')
  await expect(page.getByRole('navigation').getByRole('link', { name: 'Monitor', exact: true })).toHaveAttribute('aria-current', 'page')
  await expect(page.locator('.monitor-feed-frame')).toHaveCount(1)
  await expect(page.getByText('No signs of distress detected in this sample.')).toBeVisible()
  await expect(page.locator('.monitor-tracking')).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Acknowledge' })).toHaveCount(0)
  await page.screenshot({ path: testInfo.outputPath('monitor-normal.png'), fullPage: true })
  await page.getByLabel('Preview state').selectOption('possible-distress')
  await expect(page.locator('.monitor-page')).toHaveAttribute('data-state', 'possible-distress')
  await expect(page.locator('.monitor-tracking')).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Possible distress', exact: true })).toBeVisible()
  await expect(page.getByText('Swimmer in a coral cap', { exact: true })).toBeVisible()
  await expect(page.getByText('Limited forward movement', { exact: true })).toBeVisible()
  const feed = await page.locator('.monitor-feed-frame').boundingBox()
  const highlight = await page.locator('.monitor-tracking').boundingBox()
  expect(highlight!.x).toBeGreaterThan(feed!.x)
  expect(highlight!.y).toBeGreaterThan(feed!.y)
  expect(highlight!.x + highlight!.width).toBeLessThan(feed!.x + feed!.width)
  expect(highlight!.y + highlight!.height).toBeLessThan(feed!.y + feed!.height)
  await page.screenshot({ path: testInfo.outputPath('monitor-possible.png'), fullPage: true })
  await page.getByLabel('Preview state').selectOption('critical')
  await expect(page.getByRole('alert')).toContainText('This swimmer requires human attention now.')
  await expect(page.locator('.monitor-tracking')).toHaveCSS('border-top-color', 'rgb(217, 76, 76)')
  await page.screenshot({ path: testInfo.outputPath('monitor-critical.png'), fullPage: true })
})

test('acknowledgement preserves urgency, notification is local, and analysis stays deferred', async ({ page }) => {
  const unexpectedRequests: string[] = []
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  page.on('websocket', socket => unexpectedRequests.push(socket.url()))
  await page.route('**/*', route => {
    const request = route.request()
    if (new URL(request.url()).hostname !== 'localhost' || ['fetch', 'xhr', 'media'].includes(request.resourceType())) {
      unexpectedRequests.push(request.url()); return route.abort()
    }
    return route.continue()
  })
  await page.goto('/monitor/')
  await page.getByLabel('Preview state').selectOption('critical')
  const acknowledge = page.getByRole('button', { name: 'Acknowledge', exact: true })
  await acknowledge.focus()
  await page.keyboard.press('Enter')
  await expect(page.getByRole('button', { name: 'Acknowledged', exact: true })).toBeDisabled()
  await expect(page.getByRole('alert')).toContainText('Critical attention')
  await expect(page.locator('.monitor-tracking')).toBeVisible()
  await page.getByRole('button', { name: 'Notify Lifeguard', exact: true }).click()
  await expect(page.getByText('Notification preview recorded. No message was sent to a lifeguard.')).toBeVisible()
  await expect(page.getByRole('button', { name: 'Notification previewed' })).toBeDisabled()
  await page.getByRole('button', { name: 'Review Analysis' }).click()
  await expect(page.getByText('Analysis replay is not connected yet.')).toBeVisible()
  await expect(page.getByRole('button', { name: 'Review Analysis' })).toHaveAttribute('aria-expanded', 'true')
  expect(new URL(page.url()).pathname).toBe('/monitor/')
  await page.getByLabel('Preview state').selectOption('monitoring')
  await expect(page.locator('.monitor-tracking, .monitor-review-note')).toHaveCount(0)
  await page.getByLabel('Preview state').selectOption('critical')
  await expect(page.getByRole('button', { name: 'Acknowledge', exact: true })).toBeEnabled()
  expect(unexpectedRequests).toEqual([])
  expect(errors).toEqual([])
})

test('laptop layouts prioritize the feed and small screens reflow without overflow', async ({ page }, testInfo) => {
  await page.emulateMedia({ reducedMotion: 'reduce' })
  for (const viewport of [{ width: 1280, height: 800 }, { width: 1024, height: 768 }, { width: 768, height: 1024 }, { width: 390, height: 844 }]) {
    await page.setViewportSize(viewport)
    await page.goto('/monitor')
    await page.getByLabel('Preview state').selectOption('critical')
    await page.evaluate(() => document.fonts.ready)
    const feed = await page.locator('.monitor-feed-frame').boundingBox()
    const attention = await page.locator('.monitor-attention').boundingBox()
    if (viewport.width > 900) {
      expect(feed!.width).toBeGreaterThan(attention!.width * 1.5)
      expect(attention!.x).toBeGreaterThan(feed!.x + feed!.width)
      expect(feed!.y + feed!.height).toBeLessThanOrEqual(viewport.height)
      await expect(page.getByRole('button', { name: 'Notify Lifeguard', exact: true })).toBeInViewport({ ratio: 1 })
    } else expect(attention!.y).toBeGreaterThan(feed!.y + feed!.height)
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    expect((await page.getByRole('button', { name: 'Acknowledge', exact: true }).boundingBox())!.height).toBeGreaterThanOrEqual(48)
    await page.screenshot({ path: testInfo.outputPath(`monitor-${viewport.width}.png`), fullPage: true })
  }
})
